name: Build Docker image

on:
  push:
    paths: 
      - Dockerfile
    tags-ignore:
      - '*.*'
  pull_request:
    paths: 
      - Dockerfile

jobs:
    build:
      runs-on: self-hosted
      env:
        IMAGE_TAG: react-native
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Build Docker image
          run: docker build --tag $IMAGE_TAG .

        - name: Check if Emulator (Headless) starts
          run: docker run --rm -v "${GITHUB_WORKSPACE}/scripts/":/scripts $IMAGE_TAG /bin/sh -c "/scripts/test-emulator-headless.sh"

        - name: Checkout React Native
          uses: actions/checkout@v2
          with:
            repository: facebook/react-native
            path: react-native

        - name: Build React Native
          run: docker run --rm --ulimit nofile=10240 -v "${GITHUB_WORKSPACE}/scripts/":/scripts -v "${GITHUB_WORKSPACE}/react-native/":/react-native -w /react-native $IMAGE_TAG /bin/sh -c "/scripts/test-react-native-setup.sh"
